# Generated by Django 5.2 on 2025-04-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('ESTRELAS', 'Estrelas'), ('PLANETA', 'Planeta'), ('GALAXIA', 'Galaxia')], default='', max_length=100),
        ),
    ]
